version: 2.1
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/spaaws/aula-ci
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v
